### ISSUE TITLE
fix: make stripe checkout donation with featured image

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4348]
# Bug Report

## User Story

As an Admin, I want to be able to use a featured image on a form and still process using Stripe Checkout 2.0 so that I can receive donations.

## Current Behavior

When making a Stripe Checkout 2.0 donation from a form with a featured image, an error occurs.

## Expected Behavior

No error when making a donation from a form with a featured image.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.5.4

## Steps to Reproduce

1. Create a form with a featured image.
2. Enable Stripe Checkout 2.0
3. Attempt a donation.
4. Check the logs. This is the error:
`The Stripe Gateway returned an error while creating the Checkout Session. Details: Stripe\Error\InvalidRequest: Invalid array in /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiRequestor.php:210 from API request 'req_bn4yimUpEQaDcK'
Stack trace:
#0 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiRequestor.php(173): Stripe\ApiRequestor::_specificAPIError('{\n "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray), Array, Array)
#1 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiRequestor.php(473): Stripe\ApiRequestor->handleErrorResponse('{\n "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray), Array)
#2 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiRequestor.php(126): Stripe\ApiRequestor->_interpretResponse('{\n "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray))
#3 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiOperations/Request.php(57): Stripe\ApiRequestor->request('post', '/v1/checkout/se...', Array, Array)
#4 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/vendor/stripe/stripe-php/lib/ApiOperations/Create.php(23): Stripe\ApiResource::_staticRequest('post', '/v1/checkout/se...', Array, Array)
#5 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/includes/gateways/stripe/includes/class-give-stripe-checkout-session.php(51): Stripe\Checkout\Session::create(Array, Array)
#6 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/givewp-recurring/includes/gateways/give-recurring-stripe_checkout.php(236): Give_Stripe_Checkout_Session->create(Array)
#7 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/givewp-recurring/includes/gateways/give-recurring-stripe_checkout.php(179): Give_Recurring_Stripe_Checkout->process_stripe_checkout(5070, Array)
#8 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/givewp-recurring/includes/gateways/give-recurring-gateway.php(433): Give_Recurring_Stripe_Checkout->create_payment_profiles()
#9 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(288): Give_Recurring_Gateway->process_checkout(Array)
#10 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#11 /Users/daro/Local Sites/givecore/app/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#12 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/includes/gateways/functions.php(186): do_action('give_gateway_st...', Array)
#13 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/includes/process-donation.php(206): give_send_to_gateway('stripe_checkout', Array)
#14 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(288): give_process_donation_form(Array)
#15 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#16 /Users/daro/Local Sites/givecore/app/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#17 /Users/daro/Local Sites/givecore/app/public/wp-content/plugins/give/includes/actions.php(82): do_action('give_purchase', Array)
#18 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(288): give_post_actions('')
#19 /Users/daro/Local Sites/givecore/app/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#20 /Users/daro/Local Sites/givecore/app/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#21 /Users/daro/Local Sites/givecore/app/public/wp-settings.php(523): do_action('init')
#22 /Users/daro/Local Sites/givecore/app/public/wp-config.php(79): require_once('/Users/daro/Loc...')
#23 /Users/daro/Local Sites/givecore/app/public/wp-load.php(37): require_once('/Users/daro/Loc...')
#24 /Users/daro/Local Sites/givecore/app/public/wp-blog-header.php(13): require_once('/Users/daro/Loc...')
#25 /Users/daro/Local Sites/givecore/app/public/index.php(17): require('/Users/daro/Loc...')
#26 {main}`
## Visuals

Stripe log:
<img width="1083" alt="Screen Shot 2019-12-17 at 11 37 26 AM" src="https://user-images.githubusercontent.com/312000/71020598-41542800-20c2-11ea-855c-5218ab977092.png">

## Related

https://github.com/impress-org/givewp/issues/4281
https://secure.helpscout.net/conversation/1032190854/53055

## Acceptance Criteria

- [x]  No error when a form has a featured image

**Comment by ravinderk** [comment]
@rickalday You did not mention recurring donation in `Steps Tp Reproduce` section which is important. I was able to reproduce this issue only with a recurring donations.

**Comment by ravinderk** [comment]
@DevinWalker @rickalday Move this issue to recurring because I can only reproduce this with recurring donations
