### ISSUE TITLE
Logging system should be backward compatible

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5616]
## Details
The new logging system should work fine with the exiting addon and core.

- Do not remove publically accessible properties from class if they have used. I notice that `log_db` and `logmeta_db ` removed from `Give_Logging` and `Give`.

https://github.com/impress-org/givewp/pull/5614/files#diff-3ca2a703a24ad15fc0a69b8a0f6369b7fd6ff3cc1ba875fa5b09e60419d19a2aL32
![image](https://user-images.githubusercontent.com/1784821/108491859-71044e80-72ca-11eb-81c2-7c110e94f871.png)

```
[19-Feb-2021 09:55:43 UTC] PHP Fatal error:  Uncaught ReflectionException: Class log_db does not exist in /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php:676
Stack trace:
#0 /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php(676): ReflectionClass->__construct('log_db')
#1 /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php(595): Give\Container\Container->build('log_db')
#2 /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php(551): Give\Container\Container->resolve('log_db')
#3 /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/give.php(452): Give\Container\Container->get('log_db')
#4 /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/includes/admin/admin-actions.php(533): Give->__get('log_db')
#5 /Users/ravinderkumar/Local-Sites/extremeresponse/app/ in /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php on line 557
```

- Add newly added background migration to `install.php` to complete on a fresh install otherwise plugin user will see update notice on a fresh install.
- I am getting PHP notice when switch branch to `epic`.
```
[19-Feb-2021 06:14:27 UTC] WordPress database error Unknown error 1146 for query SELECT * FROM new_give_migrations WHERE status = 'success' made by do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, Give\Helpers\Hooks::Give\Helpers\{closure}, Give, Give->__call, Give\Container\Container->make, Give\Container\Container->resolve, Give\Container\Container->build, Give\Container\Container->Give\Container\{closure}, Give\Container\Container->build, ReflectionClass->newInstanceArgs, Give\Framework\Migrations\MigrationsRunner->__construct, Give\MigrationLog\MigrationLogRepository->getCompletedMigrationsIDs, Give\Framework\Database\DB::__callStatic, Give\Framework\Database\DB::runQueryWithErrorChecking, Give\Framework\Database\DB::Give\Framework\Database\{closure}, call_user_func_array
[19-Feb-2021 06:14:27 UTC] Query failed in database
[19-Feb-2021 06:14:27 UTC] WordPress database error Unknown error 1146 for query SELECT count(id) FROM new_give_migrations WHERE id IN ('set_paypal_standard_id_to_paypal_from_paypal_standard','create_revenue_table','remove_revenue_foreign_keys','create_migrations_table','create_new_log_table','migrate_existing_logs') AND status != 'success' made by do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, Give\Helpers\Hooks::Give\Helpers\{closure}, call_user_func_array, Give\Framework\Migrations\MigrationsRunner->run, Give\MigrationLog\MigrationLogRepository->getFailedMigrationsCountByIds, Give\Framework\Database\DB::__callStatic, Give\Framework\Database\DB::runQueryWithErrorChecking, Give\Framework\Database\DB::Give\Framework\Database\{closure}, call_user_func_array
```

- I am getting javascript notice on the log page.
![image](https://user-images.githubusercontent.com/1784821/108492638-672f1b00-72cb-11eb-9421-918665ffa530.png)

- I noticed that same property `$wpdb->give_log` defined for two tables.

## Expected Behavior

The new logging system should work with the core and exiting addon without any issue.

## Acceptance Criteria

-   [ ] All issue reported in this issue has been fixed.

**Comment by alaca** [comment]
>Do not remove publically accessible properties from class if they have used. I notice that log_db and logmeta_db removed from Give_Logging and Give.

`log_db` and `log_meta` properties should be removed as these are referencing classes that are using tables which we deleted in this update. All add-ons that are using those references will be updated as well. But maybe I'm missing something? Please let me know. 

> [19-Feb-2021 09:55:43 UTC] PHP Fatal error:  Uncaught ReflectionException: Class log_db does not exist in /Users/ravinderkumar/Local-Sites/extremeresponse/app/public/wp-content/plugins/give/src/Container/Container.php:676
Stack trace:

The last PR removed all references to that property.  If you update your local repo, this should go away. If the problem persists, it might be that one of the add-ons is using that reference. 

> Add newly added background migration to install.php to complete on a fresh install otherwise plugin user will see update notice on a fresh install.

Will do that, thanks for pointing that out. 

> I am getting PHP notice when switch branch to epic.

I can't replicate this. Try switch to the `epic` branch on a fresh install. Something probably went wrong if you switched to this branch few days ago. 

> I am getting javascript notice on the log page.

You are clearly running an old version of the `epic` branch, that explains all the problems you have now. 

Run `npm run watch` or `npm run production` for a quick fix of JS error, but I strongly recommend testing the `epic` branch on a fresh install.

**Comment by alaca** [comment]
`MigrateExistingLogs` id added to the upgrade routines list 8b1c40f1
