### ISSUE TITLE
Onboarding Settings Repository should catch invalid arguments

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5717]
## Details

Reference: https://wordpress.org/support/topic/fatal-error-uncaught-typeerror-8/

`Fatal error: Uncaught TypeError: Argument 1 passed to Give\Onboarding\SettingsRepository::__construct() must be of the type array, bool given`

<details>
Fatal error: Uncaught TypeError: Argument 1 passed to Give\Onboarding\SettingsRepository::__construct() must be of the type array, bool given, called in /home/customer/www/mysite.org/public_html/wp-content/plugins/give/src/Onboarding/SettingsRepositoryFactory.php on line 23 and defined in /home/customer/www/mysite.org/public_html/wp-content/plugins/give/src/Onboarding/SettingsRepository.php:22 Stack trace: #0 /home/customer/www/mysite.org/public_html/wp-content/plugins/give/src/Onboarding/SettingsRepositoryFactory.php(23): Give\Onboarding\SettingsRepository->__construct(false, Object(Closure)) #1 /home/customer/www/mysite.org/public_html/wp-content/plugins/give/src/Onboarding/Wizard/Page.php(49): Give\Onboarding\SettingsRepositoryFactory->make(‘give_settings’) #2 [internal function]: Give\Onboarding\Wizard\Page->__construct(Object(Give\Onboarding\FormRepository), Object(Give\Onboarding\SettingsRepositoryFactory), Object(Give\Onboarding\LocaleCollection)) #3 /home/customer/www/mysite.org/public_htm in /home/customer/www/mysite.org/public_html/wp-content/plugins/give/src/Onboarding/SettingsRepository.php on line 22
</details>

## Expected Behavior

An invalid argument type should not cause a fatal error.

## Steps to Reproduce

1. Make a new Settings Repository with a non-array value as the first parameter.

## Acceptance Criteria

-   [ ] Invalid arguments are caught and throw an exception.
-   [ ] Invalid arguments do not cause a fatal error.

**Comment by JasonTheAdams** [comment]
@kjohnson We've received further information on this issue with some steps that seem promising: https://secure.helpscout.net/conversation/1516035146/96055?folderId=672194

It seems like there's some sort of issue when cloning a site (for example production to staging) and there's a search and replace in the database.

**Comment by stevedsc** [comment]
@JasonTheAdams, this is apparently not completely fixed. I just migrated a database via SQL export/import for a prod→dev refresh, and got the following error. I was able to resolve this by deleting the plugin files and reinstalling via the WordPress admin. While the delete/reinstall is easy enough to do, maybe there’s a place for some error handling/whatever to handle a scenario like this. Cheers.

```
Fatal error: Uncaught TypeError: Give\Onboarding\SettingsRepository::__construct(): Argument #1 ($settings) must be of type array, bool given, called in /var/www/web/app/plugins/give/src/Onboarding/SettingsRepositoryFactory.php on line 25 and defined in /var/www/web/app/plugins/give/src/Onboarding/SettingsRepository.php:24 Stack trace: #0 /var/www/web/app/plugins/give/src/Onboarding/SettingsRepositoryFactory.php(25): Give\Onboarding\SettingsRepository->__construct(false, Object(Closure)) #1 /var/www/web/app/plugins/give/src/Onboarding/Wizard/Page.php(54): Give\Onboarding\SettingsRepositoryFactory->make('give_settings') #2 [internal function]: Give\Onboarding\Wizard\Page->__construct(Object(Give\Onboarding\FormRepository), Object(Give\Onboarding\SettingsRepositoryFactory), Object(Give\Onboarding\LocaleCollection)) #3 /var/www/web/app/plugins/give/src/Container/Container.php(747): ReflectionClass->newInstanceArgs(Array) #4 /var/www/web/app/plugins/give/src/Container/Container.php(244): Give\Container\Container->build('Give\\Onboarding...') #5 /var/www/web/app/plugins/give/src/Container/Container.php(703): Give\Container\Container->Give\Container\{closure}(Object(Give\Container\Container), Array) #6 /var/www/web/app/plugins/give/src/Container/Container.php(623): Give\Container\Container->build(Object(Closure)) #7 /var/www/web/app/plugins/give/src/Container/Container.php(564): Give\Container\Container->resolve('Give\\Onboarding...', Array) #8 /var/www/web/app/plugins/give/give.php(475): Give\Container\Container->make('Give\\Onboarding...') #9 /var/www/web/app/plugins/give/give.php(516): Give->__call('make', Array) #10 /var/www/web/app/plugins/give/src/Helpers/Hooks.php(41): give('Give\\Onboarding...') #11 /var/www/web/wp/wp-includes/class-wp-hook.php(307): Give\Helpers\Hooks::Give\Helpers\{closure}('') #12 /var/www/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #13 /var/www/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #14 /var/www/web/wp/wp-admin/includes/menu.php(155): do_action('admin_menu', '') #15 /var/www/web/wp/wp-admin/menu.php(394): require_once('/var/www/web/wp...') #16 /var/www/web/wp/wp-admin/admin.php(158): require('/var/www/web/wp...') #17 /var/www/web/wp/wp-admin/index.php(10): require_once('/var/www/web/wp...') #18 {main} thrown in /var/www/web/app/plugins/give/src/Onboarding/SettingsRepository.php on line 24
```

**Comment by kjohnson** [comment]
@stevedsc thanks for letting us know! It helps to track down issues when people report the problems that they encounter. I'll escalate this feedback to the team and let them know that you ran into a related issue when migrating SQL between servers.
