### ISSUE TITLE
Undefined function when trying to access to global pages

### ISSUE THREAD

**Issue by Elikill58** [impress-org/givewp#6514]
## User Story

I just install GiveWP and config everything. Now, I'm trying to access again to the webpage and it failed. I got error and a white screen of wordpress about severe error.

## Expected Behavior

Be able to access to my website.

## Steps to Reproduce

1. After new config, go to main page of wordpress website

## Visuals

Here is my error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function PGI\\Module\\PGWordPress\\Services\\Hooks\\is_checkout() in /var/www/dir/wp-content/plugins/paygreen-woocommerce/bundles/PGWordPress/Services/Hooks/StaticFilesHook.php:62
Stack trace:
#0 [internal function]: PGI\\Module\\PGWordPress\\Services\\Hooks\\StaticFilesHook->register()
#1 /var/www/dir/wp-content/plugins/paygreen-woocommerce/bundles/PGFramework/Services/Handlers/HookHandler.php(101): call_user_func_array()
#2 /var/www/dir/wp-content/plugins/paygreen-woocommerce/bundles/PGFramework/Services/Handlers/HookHandler.php(82): PGI\\Module\\PGFramework\\Services\\Handlers\\HookHandler->run()
#3 /var/www/dir/wp-includes/class-wp-hook.php(307): PGI\\Module\\PGFramework\\Services\\Handlers\\HookHandler->__call()
#4 /var/www/dir/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/dir/wp-includes/plugin.php(524): WP_Hook->do_action()
#6 /var/www/dir/wp-includes/class-wp.php(787): do_action_ref_array()
#7 /var/www/dir/wp-includes/fun in /var/www/dir/wp-content/plugins/paygreen-woocommerce/bundles/PGWordPress/Services/Hooks/StaticFilesHook.php on line 62
```

## System Information

Ubuntu 20.04, php7.4.3

## Acceptance Criteria

-   [ ] Can access to my website after updating

**Comment by jonwaldstein** [comment]
@Elikill58 that appears to be an issue with "PayGreen WooCommerce" as identified in your stack trace.  Since I don't see any trace of GiveWP, I would encourage you to reach out _PayGreen_ and see if they recognize that error.
