### ISSUE TITLE
Error message: Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, bool given

### ISSUE THREAD

**Issue by joeczucha** [impress-org/givewp#6851]
## Summary

Unable to edit pages through Wordpress dashboard due to plugin error

## Details

```
An error of type E_ERROR was caused in line 106 of the file /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php. Error message: Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, bool given in /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php:106
Stack trace:
#0 /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php(106): array_shift()
#1 [internal function]: Give\MultiFormGoals\ProgressBar\Block->localizeAssets()
#2 /var/www/html/oursite.com/app/public/content/plugins/give/src/Helpers/Hooks.php(43): call_user_func_array()
#3 /var/www/html/oursite.com/app/public/wordpress/wp-includes/class-wp-hook.php(308): Give\Helpers\Hooks::Give\Helpers\{closure}()
#4 /var/www/html/oursite.com/app/public/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/html/oursite.com/app/public/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/oursite.com/app/public/wordpress/wp-admin/edit-form-blocks.php(272): do_action()
#7 /var/www/html/oursite.com/app/public/wordpress/wp-admin/post.php(187): require('...')
#8 {main}
  thrown
```

## System Information

WordPress version 6.2.2
Active theme: Team Hope (version 0.1)
Current plugin: Give - Donation Plugin (version 2.29.2)
PHP version 8.2.7

## Temporary fix

.. plugins/give/src/MultiFormGoals/ProgressBar/Blocks.php::106
CHANGED LINE 106 FROM
    'editorColorPalette' => $editorColorPalette ? array_shift($editorColorPalette) : $defaultColorPalette,
CHANGE LINE 106 TO
    'editorColorPalette' => is_array($editorColorPalette) ? array_shift($editorColorPalette) : $defaultColorPalette,

**Comment by joeczucha** [comment]
Thanks @JoshuaHungDinh, I look forward to it being merged.
