### ISSUE TITLE
Fatal error importing donations in multisite (network)

### ISSUE THREAD

**Issue by bracketmediadev** [impress-org/givewp#7387]
PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in /wp-content/plugins/give/includes/admin/import-functions.php:809
Stack trace:
#0 /wp-content/plugins/give/includes/admin/import-functions.php(809): method_exists(false, 'get_name')
#1 /wp-content/plugins/give/includes/admin/admin-actions.php(768): give_save_import_donation_to_db(Array, Array, Array, Array)
#2 /wp-includes/class-wp-hook.php(324): give_donation_import_callback('')
#3 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wp-admin/admin-ajax.php(192): do_action('wp_ajax_give_do...')
#6 {main}
  thrown in /wp-content/plugins/give/includes/admin/import-functions.php on line 809

System report:
### WordPress Environment ###

Home URL: http://sunstg-aurora.bracketserver.com
Site URL: http://sunstg-aurora.bracketserver.com
WP Version: 6.5.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home (#340)
Page for Posts: Unset
Table Prefix Length: pa_2_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, upgraded, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: sunstg-aurora.bracketserver.com
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: LiteSpeed
PHP Version: 8.2.15
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
PHP Max Upload Size: 29 MB
cURL Version: 7.61.1, OpenSSL/1.1.1k
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 3.11.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: Few Database Migrations still need to run.
Database Tables: ✔ pa_2_give_donors✔ pa_2_give_donormeta✔ pa_2_give_comments✔ pa_2_give_commentmeta✔ pa_2_give_sessions✔ pa_2_give_formmeta✔ pa_2_give_sequential_ordering✔ pa_2_give_donationmeta✔ pa_2_give_revenue✔ pa_2_give_migrations✔ pa_2_give_log
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔Donation Processing Receipt✔New Offline Donation✔Offline Donation Instructions❌New User Registration✔User Registration Information✔Donation Note✔Email access✔Daily Email Report❌Weekly Email Report❌Monthly Email Report❌Renewal Receipt Email❌Admin Renewal Receipt Email❌Subscription Cancelled Email❌Admin Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 3.10.0
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://sunstg-aurora.bracketserver.com/donation-confirmation/
Failure Page: https://sunstg-aurora.bracketserver.com/donation-failed/
Donation History Page: https://sunstg-aurora.bracketserver.com/donor-dashboard/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Authorize.Net - Credit Card, Offline Donation
Default Payment Gateway: Authorize.Net - Credit Card
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

NOTE: this was tested on a dev environment, that's why all plugins shows as Unlicensed.

Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 3.0.1
Give - Currency Switcher: ❌ Unlicensed – by GiveWP – 2.0.3
Give - Double the Donation: Free addon – by GiveWP – 2.0.0
Give - Email Reports: ❌ Unlicensed – by GiveWP – 1.1.4
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 2.2.0
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 3.0.4
Give - Funds and Designations: ❌ Unlicensed – by GiveWP – 2.0.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 3.0.1
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.5.0
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.6.2
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 3.2.0
Give - Per Form Gateways: ❌ Unlicensed – by GiveWP – 2.0.0
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 2.6.0
Give - Tributes: ❌ Unlicensed – by GiveWP – 2.1.0
Give - Zapier: ❌ Unlicensed – by GiveWP – 1.4.2

### Other Active Plugins ###
ACF Button Image Selector: by Bracket – 1.0
ACF Columns: by Thomas Meyer – 1.2.5
ACF Content Analysis for Yoast SEO: by Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast – 3.1
Advanced Custom Fields: Field Snitch: by Stupid Studio – 1.0.3
Advanced Custom Fields: No Gutenberg: by Gabiton – 1.0.0
Advanced Custom Fields PRO: by WP Engine – 6.2.9
Bracket Anchors Tool: by Bracket – 1.0
Double the Donation: by Double the Donation – 1.1.2
Email Templates: by wpexpertsio – 1.4.3
Enable Media Replace: by ShortPixel – 4.1.5
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.4.0
WordPress Importer: by wordpressdotorg – 0.8.2

### Inactive Plugins ###

Database Management tool - Adminer: by Pexle Chris – 2.2.2
Gravity Forms: by Gravity Forms – 2.8.9
Gravity Forms reCAPTCHA Add-On: by Gravity Forms – 1.5.0
Gravity Forms User Registration Add-On: by Gravity Forms – 5.3.0
LiteSpeed Cache: by LiteSpeed Technologies – 6.1
Marker.io: by Marker.io – 1.1.9
NS Cloner - Site Copier: by Never Settle – 4.4.3
Palermo Tools: by Bracketmedia – 1.0.1
Post Duplicator: by Metaphor Creations – 2.33
Post SMTP: by Post SMTP – 2.8.13
Redirection: by John Godley – 5.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Scripts-To-Footer: by Joshua David Nelson – 0.7.2
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.94.1
WP Migrate Lite: by WP Engine – 2.6.10
WP SmartCrop: by Bytes.co – 2.0.9
Yoast SEO: by Team Yoast – 22.4

### Active MU Plugins ###

pexlechris_adminer_avoid_conflicts_with_other_plugins.php: by  –
Sunrise Camps - Network functions: by Bracketmedia – 1.0
WP Migrate Lite Compatibility: by Delicious Brains – 1.3

### Theme ###

Name: Camps
Version: 
Author URL: 
Child Theme: Yes
Parent Theme Name: Camps
Parent Theme Version: 
Parent Theme Author URL:

**Comment by bracketmediadev** [comment]
Also: if I import the CSV files as a Dry Run import, works... but real import fails. I've tested it with only one or two records and it also fails.
